// Generated by CoffeeScript 1.9.0
(function() {
  var $, CND, D, TEACUP, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper,
    __slice = [].slice;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'scratch';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  TEACUP = require('coffeenode-teacup');

  D = require('pipedreams2');

  $ = D.remit.bind(D);

  this.rpr = function(me) {
    return '\n' + CND.columnify(me, {
      paddingChr: '_'
    });
  };

  this.as_html = function(me) {
    var R, idx, list_of_close_tags, list_of_open_tags, t, text, texts, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
    R = [];
    list_of_open_tags = me[0], texts = me[1], list_of_close_tags = me[2];
    for (idx = _i = 0, _len = texts.length; _i < _len; idx = ++_i) {
      text = texts[idx];
      _ref = list_of_open_tags[idx];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        t = _ref[_j];
        R.push(t);
      }
      R.push(text);
      _ref1 = list_of_close_tags[idx];
      for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
        t = _ref1[_k];
        R.push(t);
      }
    }
    return R.join('');
  };

  this.render_open_tag = function(name, attributes) {
    return (this.render_empty_tag(name, attributes)).replace(/<\/[^>]+>$/, '');
  };

  this.render_close_tag = function(name) {
    return "</" + name + ">";
  };

  this.render_as_close_tag = function(open_tag) {
    return this.render_close_tag(open_tag.replace(/^<([^\s>]+).*$/, '$1'));
  };

  this.render_empty_tag = function(name, attributes) {
    return TEACUP.render((function(_this) {
      return function() {
        return TEACUP.TAG(name, attributes);
      };
    })(this));
  };

  this._new_hotml = function() {
    return [[], [], []];
  };

  this.slice = function(me, start, stop) {

    /* `i` for input */
    var R, i_close_tag, i_close_tags, i_list_of_close_tags, i_list_of_open_tags, i_open_tag, i_open_tags, i_texts, idx, initial_close_tags, initial_open_tags, main_idx, o_close_tags, o_list_of_close_tags, o_list_of_open_tags, o_open_tag_count, o_texts, sub_idx, tag_stack, target, _i, _j, _k, _l, _len, _len1, _m, _n, _ref, _ref1, _ref2, _ref3;
    i_list_of_open_tags = me[0], i_texts = me[1], i_list_of_close_tags = me[2];

    /* `o` for output */
    _ref = R = this._new_hotml(), o_list_of_open_tags = _ref[0], o_texts = _ref[1], o_list_of_close_tags = _ref[2];
    if (start >= stop) {
      return R;
    }
    start = Math.max(start, 0);
    stop = Math.min(stop, i_texts.length - 1);
    o_open_tag_count = 0;
    tag_stack = [];
    initial_open_tags = [];
    initial_close_tags = [];
    o_list_of_open_tags.push(initial_open_tags);
    o_texts.push('');
    o_list_of_close_tags.push(initial_close_tags);

    /* Walking backwards from `start` to the beginning, collecting closing and opening tags: */
    for (main_idx = _i = _ref1 = start - 1; _i >= 0; main_idx = _i += -1) {
      i_open_tags = i_list_of_open_tags[main_idx];
      i_close_tags = i_list_of_close_tags[main_idx];
      o_open_tag_count -= i_close_tags.length;
      for (sub_idx = _j = _ref2 = i_open_tags.length - 1; _j >= 0; sub_idx = _j += -1) {
        o_open_tag_count += 1;
        if (!(o_open_tag_count > 0)) {
          continue;
        }
        tag_stack.unshift(i_open_tags[sub_idx]);
        initial_open_tags.unshift(i_open_tags[sub_idx]);
      }
    }

    /* Walking forward through the slice: */
    for (main_idx = _k = start; _k < stop; main_idx = _k += +1) {
      i_open_tags = i_list_of_open_tags[main_idx];
      i_close_tags = i_list_of_close_tags[main_idx];
      o_close_tags = [];
      o_open_tag_count += i_open_tags.length;
      o_open_tag_count -= i_close_tags.length;
      for (_l = 0, _len = i_open_tags.length; _l < _len; _l++) {
        i_open_tag = i_open_tags[_l];
        tag_stack.push(i_open_tag);
      }
      if (main_idx === start) {
        initial_open_tags.push.apply(initial_open_tags, i_open_tags);
        o_texts[0] = i_texts[main_idx];
        initial_close_tags.push.apply(initial_close_tags, i_close_tags);
      } else {
        o_list_of_open_tags.push(CND.LODASH.clone(i_open_tags));
        o_texts.push(i_texts[main_idx]);
        o_list_of_close_tags.push(CND.LODASH.clone(i_close_tags));
      }
      for (_m = 0, _len1 = i_close_tags.length; _m < _len1; _m++) {
        i_close_tag = i_close_tags[_m];
        tag_stack.pop();
      }
    }

    /* Closing all remaining open tags: */
    if (tag_stack.length > 0) {
      target = CND.last_of(o_list_of_close_tags);
      for (idx = _n = _ref3 = tag_stack.length - 1; _ref3 <= 0 ? _n <= 0 : _n >= 0; idx = _ref3 <= 0 ? ++_n : --_n) {
        target.push(this.render_as_close_tag(tag_stack[idx]));
      }
    }
    return R;
  };

  this.parse = function(html, handler) {
    CND.validate_isa_function(handler);
    this._parse(html, handler);
    return null;
  };

  this.$parse = function(html) {
    throw new Error("not implemented");
  };

  this._parse = function(html, handler) {
    var input, _send;
    if (handler == null) {
      handler = null;
    }
    input = D.create_throughstream();
    _send = null;
    if (handler == null) {
      handler = (function(_this) {
        return function(error, hotml) {
          if (error) {
            return _send.error(error);
          }
          return _send(hotml);
        };
      })(this);
    }
    input.pipe(D.HTML.$parse()).pipe((function(_this) {
      return function() {
        var Z, close_tags, last_type, open_tags, texts, _ref;
        _ref = Z = _this._new_hotml(), open_tags = _ref[0], texts = _ref[1], close_tags = _ref[2];
        last_type = null;
        return $(function(event, send) {
          var tail, type;
          _send = send;
          type = event[0], tail = 2 <= event.length ? __slice.call(event, 1) : [];
          switch (type) {
            case 'text':
            case 'lone-tag':
              switch (last_type) {
                case null:
                case 'close-tag':
                case 'lone-tag':
                case 'text':
                  open_tags.push([]);
                  texts.push(type === 'text' ? tail[0] : _this.render_open_tag.apply(_this, tail));
                  close_tags.push([]);
                  break;
                case 'open-tag':
                  texts[texts.length - 1] = tail[0];
                  break;
                default:
                  return handler(new Error("1 ignored event of type " + (rpr(type))));
              }
              break;
            case 'open-tag':
              switch (last_type) {
                case null:
                case 'text':
                case 'lone-tag':
                case 'close-tag':
                  open_tags.push([_this.render_open_tag.apply(_this, tail)]);
                  texts.push('');
                  close_tags.push([]);
                  break;
                case 'open-tag':
                  (CND.last_of(open_tags)).push(_this.render_open_tag.apply(_this, tail));
                  break;
                default:
                  return handler(new Error("2 ignored event of type " + (rpr(type))));
              }
              break;
            case 'close-tag':
              switch (last_type) {
                case null:
                  throw new Error("encountered illegal HTML");
                  break;
                case 'text':
                case 'lone-tag':
                case 'close-tag':
                case 'open-tag':
                  (CND.last_of(close_tags)).push(_this.render_close_tag.apply(_this, tail));
                  break;
                default:
                  return handler(new Error("3 ignored event of type " + (rpr(type))));
              }
              break;
            case 'end':
              handler(null, Z);
              break;
            default:
              return handler(new Error("4 ignored event of type " + (rpr(type))));
          }
          last_type = type;
          return send(Z);
        });
      };
    })(this)());
    input.write(html);
    return input.end();
  };

  this.demo = function() {
    var html;
    html = "lo <div id='mydiv'><em><i>arc <b>bo</b> cy <span class='foo'></span> dean</i></em> eps <img src='x.jpg'> foo gig hey</div>";
    return this.parse(html, (function(_this) {
      return function(error, hotml) {
        var start, stop, _i;
        if (error != null) {
          throw error;
        }
        start = 5;
        for (stop = _i = 5; _i <= 9; stop = ++_i) {
          urge(start, stop, _this.rpr(_this.slice(hotml, start, stop)));
          info(start, stop, _this.as_html(_this.slice(hotml, start, stop)));
        }
        urge(JSON.stringify(hotml));
        help(_this.rpr(hotml));
        return info(_this.as_html(hotml));
      };
    })(this));
  };

  if (module.parent == null) {
    this.demo();
  }

}).call(this);
