// Generated by CoffeeScript 1.9.1
(function() {
  this.MD = {};

  this.MD.$as_html = function() {
    var parser;
    parser = PIPEDREAMS.HOTMETAL.MD.new_parser();
    return $((function(_this) {
      return function(md, send) {
        return send(PIPEDREAMS.HOTMETAL.MD.as_html(md, parser));
      };
    })(this));
  };

  this.MD = {};

  this.MD.new_parser = (function(_this) {
    return function(settings) {
      var R, source_references;
      if (settings != null) {
        throw new Error("settings not yet supported");
      }
      settings = {
        html: true,
        linkify: false,
        breaks: false,
        langPrefix: 'codelang-',
        typographer: true,
        quotes: '“”‘’'
      };
      source_references = require('coffeenode-markdown-it/lib/rules_core/source_references');
      R = (require('coffeenode-markdown-it'))(settings);

      /* TAINT now is the time to active settings */
      R = R.use(source_references);
      return R;
    };
  })(this);

  this.MD.as_html = (function(_this) {
    return function(md, parser) {
      if (parser == null) {
        parser = null;
      }
      return (parser != null ? parser : _this.MD.new_parser()).render(md);
    };
  })(this);

}).call(this);
