// Generated by CoffeeScript 1.9.1
(function() {
  var $, CND, D, HOTMETAL, badge, rpr;

  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = 'HOTMETAL/MARKDOWN';

  HOTMETAL = require('..');

  D = require('pipedreams2');

  $ = D.remit.bind(D);

  this.new_parser = (function(_this) {
    return function(settings) {
      var R, source_references;
      if (settings != null) {
        throw new Error("settings not yet supported");
      }
      settings = {
        html: true,
        linkify: false,
        breaks: false,
        langPrefix: 'codelang-',
        typographer: true,
        quotes: '“”‘’'
      };
      source_references = require('coffeenode-markdown-it/lib/rules_core/source_references');
      R = (require('coffeenode-markdown-it'))(settings);

      /* TAINT now is the time to active settings */
      R = R.use(source_references);
      return R;
    };
  })(this);

  this.as_html = (function(_this) {
    return function(md, parser) {
      if (parser == null) {
        parser = null;
      }
      return (parser != null ? parser : _this.new_parser()).render(md);
    };
  })(this);

  this.$as_html = function() {
    var parser;
    parser = this.new_parser();
    return $((function(_this) {
      return function(md, send) {
        return send(_this.as_html(md, parser));
      };
    })(this));
  };

}).call(this);
