// Generated by CoffeeScript 1.9.1
(function() {
  this.TYPO = {};

  this.TYPO.$quotes = function() {
    return $((function(_this) {
      return function(text, send) {
        return send(PIPEDREAMS.HOTMETAL.TYPO.quotes(text));
      };
    })(this));
  };

  this.TYPO.$dashes = function() {
    return $((function(_this) {
      return function(text, send) {
        return send(PIPEDREAMS.HOTMETAL.TYPO.dashes(text));
      };
    })(this));
  };

  this.TYPO = {};

  this.TYPO.quotes = (function(_this) {
    return function(text) {
      return (require('typogr')).smartypants(text);
    };
  })(this);

  this.TYPO.dashes = (function(_this) {
    return function(text) {
      return (require('typogr')).smartypants(text);
    };
  })(this);

}).call(this);
