// Generated by CoffeeScript 1.9.1
(function() {
  var $, CND, D, HOTMETAL, badge, rpr;

  CND = require('cnd');

  rpr = CND.rpr.bind(CND);

  badge = 'HOTMETAL/HYPHENATOR';

  HOTMETAL = require('..');

  D = require('pipedreams2');

  $ = D.remit.bind(D);

  this.quotes = (function(_this) {
    return function(text) {
      return (require('typogr')).smartypants(text);
    };
  })(this);

  this.dashes = (function(_this) {
    return function(text) {
      return (require('typogr')).smartypants(text);
    };
  })(this);

  this.$quotes = function() {
    return $((function(_this) {
      return function(text, send) {
        return send(_this.quotes(text));
      };
    })(this));
  };

  this.$dashes = function() {
    return $((function(_this) {
      return function(text, send) {
        return send(_this.dashes(text));
      };
    })(this));
  };

}).call(this);
